# Generated by Django 3.0.6 on 2020-06-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bexrooms',
            new_name='bedrooms',
        ),
    ]
