# Generated by Django 3.0.6 on 2020-06-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200610_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_publlished',
            new_name='is_published',
        ),
    ]
